#!python
import glob
import os
import numpy as np
import pandas as pd

# setup the output files 
dataset_paths = glob.glob("data/datasets/*")
qs = []
ps = []
for dataset_path in dataset_paths:
    dataset = os.path.basename(dataset_path)
    bed_path = glob.glob("{}/*.bed".format(dataset_path))[0]
    prefix = os.path.basename(bed_path).split(".")[0]
    for k in range(2, 12):
        for r in range(1):
            qs.append("output/admixture/{}/{}.K{}r{}.Q".format(dataset, prefix, k, r + 1))
            ps.append("output/admixture/{}/{}.K{}r{}.P".format(dataset, prefix, k, r + 1))


rule admixture_all:
    """Runs all admixture rules
    """
    input:
        qs,
        ps


rule run_admixture:
    """Runs admixture
    """
    input:
        bed = "data/datasets/{dataset}/{prefix}.bed"
    params:
        K = "{K}",
        r = "{r}",
        q = "./{prefix}.{K}.Q",
        p = "./{prefix}.{K}.P"
    output:
        q="output/admixture/{dataset}/{prefix}.K{K}r{r}.Q",
        p="output/admixture/{dataset}/{prefix}.K{K}r{r}.P"
    run:
        shell("admixture -s ${{RANDOM}} {input.bed} {params.K} -j8")
        shell("mv {params.p} {output.p}")
        shell("mv {params.q} {output.q}")
