---
title: "Fitting a real-data covariance matrix"
author: "Jason Willwerscheid"
date: "9/11/2020"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: false
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, collapse = TRUE, comment = "#>",
                      fig.width = 8, fig.height = 6.5)
```

```{r load.pkgs}
suppressMessages({
  library(flashier)
  library(drift.alpha)
  library(tidyverse)
})
```

I fit flash to the covariance matrix of the `1kg_phase3_derived` dataset using point-Laplace priors. I show results from the greedy fit, backfit, and `LL' + D` fit.

```{r dat}
covmat <- readRDS("../data/datasets/1kg_phase3_derived/1kg_phase3_derived_covmat.rds")
meta <- readRDS("../data/datasets/1kg_phase3_derived/1kg_phase3_derived_meta.rds")

plot_fl <- function(LL) {
  df <- data.frame(LL)
  colnames(df) <- paste0("Factor ", formatC(1:ncol(LL), width = 2, flag = "0"))
  df$subpop <- meta$pop
  df$superpop <- meta$super_pop
  df <- df %>% arrange(superpop)
  df$idx <- 1:nrow(df)
  gath_df <- df %>% 
    gather(K, value, -subpop, -idx, -superpop) %>%
    mutate(K = factor(K))
  med_gath_df <- gath_df %>% 
    group_by(subpop, K) %>% 
    summarise(value=median(value), idx=median(idx))
  
  p <- ggplot(gath_df, aes(x=idx, y=value, color=superpop)) + 
    geom_point() +
    facet_wrap(~K) + 
    geom_hline(yintercept = 0, linetype = "dashed") +
    theme(axis.title.x=element_blank(),
          axis.text.x=element_blank(),
          axis.ticks.x=element_blank()) +
    labs(color="superpop")
  return(p)
}
```

## Greedy fit

```{r pl_g}
fl_g <- flash.init(covmat) %>%
  flash.set.verbose(0) %>%
  flash.add.greedy(Kmax = 20, 
                   prior.family = prior.point.laplace())

plot(plot_fl(fl_g$loadings.pm[[1]] %*% diag(sqrt(fl_g$loadings.scale))))
```

## Backfit

```{r pl_bf}
fl_bf <- fl_g %>% flash.backfit()

plot(plot_fl(fl_bf$loadings.pm[[1]] %*% diag(sqrt(fl_bf$loadings.scale))))
```

## Additional diagonal variance

```{r diag}
n <- nrow(covmat)

fl <- fl_bf
diag_S2 <- mean(diag(covmat)^2 
                - 2 * diag(covmat) * rowSums(fl$flash.fit$EF[[1]] * fl$flash.fit$EF[[2]])
                + rowSums(fl$flash.fit$EF2[[1]] * fl$flash.fit$EF2[[2]])
                - rowSums(fl$flash.fit$EF[[1]]^2 * fl$flash.fit$EF[[2]]^2))
diag_S2 <- diag_S2 + sum(crossprod(fl$flash.fit$EF[[1]] * fl$flash.fit$EF[[2]])) / n
diag_S2 <- diag_S2 - 1 / fl$flash.fit$tau
  
elbo_diff <- Inf
while (elbo_diff > 0.1) {
  old_elbo <- fl$elbo
  fl <- flash.init(covmat, S = diag(rep(sqrt(diag_S2), n)), var.type = 0) %>%
    flash.set.verbose(0) %>%
    flash.init.factors(EF = fl$flash.fit$EF, EF2 = fl$flash.fit$EF2,
                       prior.family = prior.point.laplace()) %>%
    flash.backfit()
  cat("SD (diagonal):", formatC(sqrt(diag_S2), format = "e", digits = 2),
      " SD (non-diag):", formatC(sqrt(1 / fl$flash.fit$tau[1, 2]), format = "e", digits = 2),
      " ELBO:", fl$elbo, "\n")
  elbo_diff <- fl$elbo - old_elbo
  
  diag_S2 <- mean(diag(covmat)^2 
                  - 2 * diag(covmat) * rowSums(fl$flash.fit$EF[[1]] * fl$flash.fit$EF[[2]])
                  + rowSums(fl$flash.fit$EF2[[1]] * fl$flash.fit$EF2[[2]])
                  - rowSums(fl$flash.fit$EF[[1]]^2 * fl$flash.fit$EF[[2]]^2))
  diag_S2 <- diag_S2 + sum(crossprod(fl$flash.fit$EF[[1]] * fl$flash.fit$EF[[2]])) / n
  diag_S2 <- diag_S2 - 1 / fl$flash.fit$tau[1, 2]
}

plot(plot_fl(fl$loadings.pm[[1]] %*% diag(sqrt(fl$loadings.scale))))
```

## Drift

```{r dr}
LL <- fl$loadings.pm[[1]] %*% diag(sqrt(fl$loadings.scale))
LL <- cbind(abs(LL[, 1]), pmax(LL[, -1], 0), pmax(-LL[, -1], 0))
LL <- LL[, c(1, 2 * (1:11), 2 * (1:11) + 1)]
# LL <- LL[, -c(3, 7, 12, 14, 16, 18, 21, 22)] # by inspection

LL_scale <- apply(LL, 2, max)
LL <- t(t(LL) / LL_scale)

which_k <- (LL_scale > .01)
LL <- LL[, which_k]
LL_scale <- LL_scale[which_k]

dr <- init_from_covmat(covmat, LL, p = 10000, prior.s2 = LL_scale^2)
dr <- drift(dr, maxiter = 200, verbose = FALSE)

plot(plot_fl(dr$EL %*% diag(sqrt(dr$prior_s2))))
```
