---
title: "Greedy Tree"
author: "jhmarcus"
date: "2019-05-28"
output: workflowr::wflow_html
---

# Import

Here I import the some required packages:

```{r imports, message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(ashr)
library(flashier)
source("../code/viz.R")
source("../code/sim.R")
source("../code/bern.R")
```

# Functions

```{r}
plot_flash_loadings = function(flash_fit, n_per_pop){

  l_df = as.data.frame(flash_fit$fit$EF[[1]])
  colnames(l_df) = 1:ncol(l_df)
  l_df$ID = 1:nrow(l_df)
  l_df$pop = c(rep("Pop1", n_per_pop), rep("Pop2", n_per_pop),
               rep("Pop3", n_per_pop), rep("Pop4", n_per_pop))
  
  gath_l_df = l_df %>% gather(K, value, -ID, -pop) 

  p1 = ggplot(gath_l_df, aes(x=ID, y=value, color=pop)) + 
       geom_point() +
       facet_wrap(K~., scale="free") +
       theme_bw() 
  
  p2 = structure_plot(gath_l_df %>% filter(K!=1), 
                      colset="Set3", 
                      facet_grp="pop", 
                      facet_levels=paste0("Pop", 1:4),
                      keep_leg=TRUE,
                      fact_type="nonnegative") 
  
  return(list(p1=p1, p2=p2))
  
}

my.init.fn <- function(flash, tol, maxiter) {
  
  EF <- flashier:::init.next.EF(flash, tol, maxiter)

  # Rescale so that L has range 0 to 1.
  l.scale <- max(abs(EF[[1]])) * sign(which.max(abs(EF[[1]])))
  EF[[1]] <- EF[[1]] / l.scale
  EF[[2]] <- EF[[2]] * l.scale
  
  return(EF)
  
}
```

# Simulate

Here I simulate a simple tree found [here](simpler_tree_simulation.html) with the below parameter settings:

```{r}
set.seed(123)
n_per_pop = 20
sigma_e = .1
p = 10000
sim_res = simpler_tree_simulation(n_per_pop, p, sigma_e)
Y = sim_res$Y

l_df = as.data.frame(sim_res$L)
colnames(l_df) = 1:ncol(l_df)
l_df$ID = 1:nrow(l_df)
l_df$pop = c(rep("Pop1", n_per_pop), rep("Pop2", n_per_pop),
             rep("Pop3", n_per_pop), rep("Pop4", n_per_pop))
gath_l_df = l_df %>% gather(K, value, -ID, -pop) 
p = ggplot(gath_l_df, aes(x=ID, y=value, color=pop)) + 
    geom_point() +
    facet_wrap(K~., scale="free") +
    theme_bw() 
p
```

# Bimodal prior

Here I specify the grid of the prior

```{r}
# bimodal g prior list used throughout
m = 40
b = seq(1.0, 0.0, length=m)
a = seq(0.0, 1.0, length=m)

bimodal_prior = rep(1, 2*m)
bimodal_prior[c(1, m + 1)] = 10

bimodal_g = ashr:::unimix(rep(0, 2*m), c(rep(0, m), b), c(a, rep(1, m)))
bimodal_g
```

# Bimodal (Greedy)

```{r warning=FALSE, message=FALSE}
flash_fit_g0 = flashier::flashier(Y, 
                                 greedy.Kmax=1,
                                 prior.type=c("nonnegative", "point.normal"),
                                 ash.param=list(fixg=FALSE, g=bimodal_g, method=NULL),
                                 ebnm.param=list(fix_pi0=TRUE, g=list(pi0=0)),
                                 fixed.factors = c(flashier:::ones.factor(n = 1)),
                                 var.type=0,                                                            
                                 backfit="final"
                                 )

Lhat = flash_fit_g0$fit$EF[[1]]
p_res = plot_flash_loadings(flash_fit_g0, n_per_pop)
print(p_res$p1)
```

```{r}
Yhat = flash_fit_g0$fit$EF[[1]] %*% t(flash_fit_g0$fit$EF[[2]])
flash_fit_g1 = flashier::flashier(Y-Yhat, 
                                 greedy.Kmax=0,
                                 prior.type=c("nonnegative", "point.normal"),
                                 ash.param=list(fixg=FALSE, g=bimodal_g, method=NULL),
                                 ebnm.param=list(fix_pi0=TRUE, g=list(pi0=0)),
                                 fixed.factors = flashier:::sparse.factors(n=1, nz.idx=c(41:80)),
                                 var.type=0,                                                            
                                 backfit="final"
                                 )

Lhat = flash_fit_g1$fit$EF[[1]]
p_res = plot_flash_loadings(flash_fit_g1, n_per_pop)
print(p_res$p1)
```

```{r}
Yhat1 = flash_fit_g1$fit$EF[[1]] %*% t(flash_fit_g1$fit$EF[[2]])
flash_fit_g1 = flashier::flashier(Y-Yhat-Yhat1, 
                                 greedy.Kmax=0,
                                 prior.type=c("nonnegative", "point.normal"),
                                 ash.param=list(fixg=FALSE, g=bimodal_g, method=NULL),
                                 ebnm.param=list(fix_pi0=TRUE, g=list(pi0=0)),
                                 fixed.factors = flashier:::sparse.factors(n=1, nz.idx=c(41:80)),
                                 var.type=0,                                                            
                                 backfit="none"
                                 )

Lhat = flash_fit_g1$fit$EF[[1]]
p_res = plot_flash_loadings(flash_fit_g1, n_per_pop)
print(p_res$p1)
```