---
title: "hoa_global_bimodal"
author: "Joseph Marcus"
date: "2020-04-30"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Imports

Lets import some needed packages:

```{r imports, warning=FALSE, message=FALSE}
#setwd("/project2/mstephens/jhmarcus/drift-workflow/analysis/")
library(ggplot2)
library(tidyr)
library(dplyr)
library(RColorBrewer)
library(knitr)
source("../code/structure_plot.R")

get_pops = function(meta_df, region){
    
  pops = meta_df %>% filter(Region==region) %>% 
         dplyr::select(Region, Simple.Population.ID, Latitude) %>%
         distinct(Simple.Population.ID, Latitude) %>% 
         arrange(desc(Latitude)) %>% 
         pull(Simple.Population.ID)
    
    return(pops)
  
}
```

# Data 

Lets first read the greedy `flashier` fit

```{r flash-greedy}
# read the flash fit output by snakemake
method <- "drift"
Kmax <- 9
colors <- brewer.pal(n = Kmax-1, name = "Set2")
filetype <- ".png"
rds_path <- paste0("../output/", 
                  method,
                  "/hoa_global/HumanOriginsPublic2068_auto_maf05_geno005_mind02_K", 
                  Kmax, 
                  ".rds")
fl <- readRDS(rds_path)

if(method=="drift"){
  EL <- fl$EL %*% diag(sqrt(fl$prior_s2))
} else {
  EL <- fl$flash.fit$EF[[1]]
}
n <- nrow(EL)
print(Kmax)
print(n)
```

```{r}
# read the meta data
meta_df <- read.table("../data/meta/HumanOriginsPublic2068.meta", sep="\t", header=T)

# setup loadings data.frame
l_df <- as.data.frame(EL)
colnames(l_df) <- paste0(1:Kmax)
inds <- read.table("../data/datasets/hoa_global/HumanOriginsPublic2068_auto_maf05_geno005_mind02.fam", 
                  header=F, stringsAsFactors=F) %>% pull(V2)
l_df$ID <- inds
l_df <- l_df %>% inner_join(meta_df, by="ID")
# all unique pop labels
#pops = unique(l_df$Simple.Population.ID) 
# join with the meta data
#l_df = l_df %>% arrange(Region, Simple.Population.ID) # sort by region then by population
#l_df$ID = factor(l_df$ID, levels=l_df$ID) # make sure the ids are sorted
head(l_df)
```

## Africa

```{r}
region = "Africa"
l_pop_df <- l_df %>% filter(Region == region)
pops = get_pops(meta_df, region)
labels <- as.vector(droplevels(l_pop_df$Simple.Population.ID))
label_order <- as.vector(droplevels(pops))
p <- create_structure_plot(l_pop_df[,2:Kmax], 
                           labels=labels, 
                           label_order=label_order,
                           label_font_size=6, 
                           colors=colors)
p
```

## West Eurasia

```{r}
region = "WestEurasia"
l_pop_df <- l_df %>% filter(Region == region)
pops = get_pops(meta_df, region)
labels <- as.vector(droplevels(l_pop_df$Simple.Population.ID))
label_order <- as.vector(droplevels(pops))
p <- create_structure_plot(l_pop_df[,2:Kmax], 
                           labels=labels, 
                           label_order=label_order,
                           label_font_size=6, 
                           colors=colors)
p
```

## America

```{r}
region = "America"
colors <- brewer.pal(n = 8, name = "Set2")
l_pop_df <- l_df %>% filter(Region == region)
pops = get_pops(meta_df, region)
labels <- as.vector(droplevels(l_pop_df$Simple.Population.ID))
label_order <- as.vector(droplevels(pops))
p <- create_structure_plot(l_pop_df[,2:Kmax], 
                           labels=labels, 
                           label_order=label_order,
                           label_font_size=6, 
                           colors=colors)
p
```

## Central Asia Siberia

```{r}
region = "CentralAsiaSiberia"
l_pop_df <- l_df %>% filter(Region == region)
pops = get_pops(meta_df, region)
labels <- as.vector(droplevels(l_pop_df$Simple.Population.ID))
label_order <- as.vector(droplevels(pops))
p <- create_structure_plot(l_pop_df[,2:Kmax], 
                           labels=labels, 
                           label_order=label_order,
                           label_font_size=6, 
                           colors=colors)
p
```

## East Asia

```{r}
region = "EastAsia"
l_pop_df <- l_df %>% filter(Region == region)
pops = get_pops(meta_df, region)
labels <- as.vector(droplevels(l_pop_df$Simple.Population.ID))
label_order <- as.vector(droplevels(pops))
p <- create_structure_plot(l_pop_df[,2:Kmax], 
                           labels=labels, 
                           label_order=label_order,
                           label_font_size=6, 
                           colors=colors)
p
```

## South Asia

```{r}
region = "SouthAsia"
l_pop_df <- l_df %>% filter(Region == region)
pops = get_pops(meta_df, region)
labels <- as.vector(droplevels(l_pop_df$Simple.Population.ID))
label_order <- as.vector(droplevels(pops))
p <- create_structure_plot(l_pop_df[,2:Kmax], 
                           labels=labels, 
                           label_order=label_order,
                           label_font_size=6, 
                           colors=colors)
p
```

## Oceania

```{r}
region = "Oceania"
l_pop_df <- l_df %>% filter(Region == region)
pops = get_pops(meta_df, region)
labels <- as.vector(droplevels(l_pop_df$Simple.Population.ID))
label_order <- as.vector(droplevels(pops))
p <- create_structure_plot(l_pop_df[,2:Kmax], 
                           labels=labels, 
                           gap=1,
                           label_order=label_order,
                           label_font_size=6, 
                           colors=colors)
p
```