---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
---

**Authors:** Joe Marcus and Jason Willwerscheid   
**Advisors:** John Novembre, Peter Carbonetto, and Matthew Stephens

# Current

## Simulations

* [Simple 2 population tree simulation](simple_2pop_tree_simulation_bimodal.html)
* [Simple admixture event](admix_sim1.html)
* [Branching + admixture: initialization](admix_sim4.html)
* [Branching + admixture: larger p, longer runs](admix_sim5.html)

Less simple admixture event:

* [Part I](admix_sim_full.html)
* [Part II: larger $p$, larger $w$](admix_sim_full2.html)
* [Part III: larger $n$, smaller $w$](admix_sim_full3.html)

Coalescent simulations:

* [OutOfAfrica_2T12](OutOfAfrica_2T12.html)  
* [OutOfAfrica_3G09](OutOfAfrica_3G09.html)
* [AmericanAdmixture_4B11](AmericanAdmixture_4B11.html)

Coalescent simulations with fixed shared factor:

* [OutOfAfrica_3G09](OutOfAfrica_3G09_fix.html)
* [AmericanAdmixture_4B11](AmericanAdmixture_4B11_fix.html)

Four-population tree:

* [Simple tree, with strategies for getting from default drift fit to optimal tree](tree_adjust.html)

## Explorations

* [Empircal Bayes Normal Means with Bimodal Priors](ebnm_bimodal.html)
* [Empircal Bayes Normal Means with Bernoulli Priors](ebnm_bern.html)
* [Using a penalized ELBO to encourage orthogonal factors](ortho_2pop_admix.html)

## Data Preparation

These vignettes describe data preparation steps:

* [Human Origins Array Global Data](data_hoa_global.html) 

## Data Applications

* [hoa global drift fits](hoa_global_drift_bimodal.html) 

---

# Deprecated

*Before 2019-12-01*:

## Exploration

These vignettes describe exploratory ideas:

* [FLASH proof of principle](flash.html)

## Results

These vignettes describe results on simulated / empirical data:

* [Human Origins Array Global](hoa_global.html)  
* [Alternative view of Human Origins factors](hoa_global_alt.html)

## Simulations

* [Simple Tree Simulation](simple_tree_simulation.html)
* [Simpler Tree Simulation](simpler_tree_simulation.html)
* [Simpler Tree Simulation (bimodal)](simpler_tree_simulation_bimodal.html)
* [Simplest Tree Simulation (bimodal)](simplest_tree_simulation_bimodal.html)
* [badMIXTURE (in progress)](badmixture.html)
