---
title: "OutOfAfrica_3G09"
author: "Joseph Marcus"
date: "2020-04-26"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Imports

```{r}
suppressMessages({
  library(lfa)
  library(flashier)
  library(drift.alpha)
  library(ggplot2)
  library(reshape2)
  library(tidyverse)
})
```

# Read the simulation data

```{r}
Y <- t(lfa::read.bed("../output/simulations/OutOfAfrica_3G09/rep0_maf_ldprune"))
Z <- scale(Y)
n <- nrow(Y)
p <- ncol(Y)

# sub-population labels from stdpop
labs <- rep(c("YRI", "CEU", "HAN"), each=20)
```

# Run PCA

```{r}
svd_res <- lfa:::trunc.svd(Y, 4)
L_hat <- svd_res$u
plot_loadings(L_hat, labs)
```

```{r}
library(alstructure)

admix_res <- alstructure::alstructure(t(Y), d_hat=)
Qhat <- t(admix_resQ_hat)

plot_loadings(Qhat, labs)

```

# Run greedy flash

```{r}
ones <- matrix(1, nrow = nrow(Y), ncol = 1)
ls.soln <- t(solve(crossprod(ones), crossprod(ones, Y)))
#fl <- flash.init(Y, var.type = 2) %>%
#      flash.init.factors(EF = list(ones, ls.soln)) %>%
#      flash.fix.loadings(kset=1, mode = 1L) %>%
#      flash.backfit() %>%
#      flash.add.greedy(Kmax = 4, prior.family=c(prior.bimodal(), prior.normal()))


fl <- flash(Y, greedy.Kmax=5, prior.family=c(prior.bimodal(), prior.normal()))

plot_loadings(fl$flash.fit$EF[[1]], labs)
```



# Run drift

With greedy intialization:

```{r}
drift.rand <- drift(init, miniter=2, maxiter=500, tol = 0.01, verbose = TRUE)

```

## Plot the loadings 

```{r}
plot_loadings(drift.rand$EL, labs)
```
